# brew packages are packages for the command line
brew_packages:
- asciidoctor
- awscli
- bind
- btop
- colordiff
- direnv
- eza
- fd
- git
- git-delta
- gcloud-cli
- graphviz
- helm
- htop
- hugo
- imagemagick
- jq
- k9s
- kubernetes-cli
- lesspipe
- lynx
- neomutt
- nmap
- nvim
- oathtool
- offlineimap
- opentofu
- pandoc
- plantuml
- pgcli
- ripgrep
- stow
- tree
- urlscan
- uuid
- whois
- zoxide

# brew casks are visual programms
brew_casks:
- alacritty
- enpass
- firefox
- firefox@developer-edition
- gimp
- gnucash
- google-chrome
- kitty
- spotify
- ungoogled-chromium

# mas apps are apps from the apple app-store
mas_apps: []

