$ANSIBLE_VAULT;1.1;AES256
62316133353037356566653437653261346466653563313132376436646338353936323262323032
6335346266346332333031633261333765326132616238300a613333363865356638656364386335
64333961323131333762663935363639666661643363386330353837333633653265316637316264
3461366634383432350a623234346462383832323462353464313065613932613234633537346334
38626464313764396237633033633930326532396433653535373337393736663238343739646339
38336530383339373565393464323763613133346562663835376437663539346465636331633537
37396666633963323564633562323937623338626465366335333531383334303935323764383833
39383831303332623366646338333333663135633139393631333637633664363833373930626365
65386535333636313332363338343031633961353861663363336334343332643933356461343537
66663637363132346334626565643062333163613036666237393531383336393132306665393535
38373537653465306132356266633236396263343665306666333564303230663530623037353265
38373733333462663463623134366236313138396139646466353062383634623735386463373531
34373563623561366461303438663463396537636231373334363832613861656162363833386631
35643736363866613633336432306639646666653035323866386537396432633933626333356362
63333135353063663238373562643539376334643339376430663832633463306165313033623839
35353736343138323661386161343639623036643365613333633331616134316538383538386231
3539
