$ANSIBLE_VAULT;1.1;AES256
61663465363061373431636662323362666162636163393034363666306566316338613563363135
6338396538323236336432613866386663613664383433620a366135306239653936653361383266
34636165363333653834393831666261396330363634646338643638326231386233386434313962
3339313464616238380a633533623666633936363265386161643030326362633630393134323237
62616464303563373438666433316134643732326630343131396430323031376139303739383863
62646363646330636664356234666636626131306364353738393963353862663864656239373338
65373338353534396234303064306539306438623739613163306435393433313536336361373031
64323261643863323237616565623239643432333864666633393033343963646464343735646131
64656637653132356634316531376536616136396533666563373934363939613761393762326530
65386532623931653162383235306434353939316666333665656331386439313365666130393334
36623263623736633761613838373633613738616436393765383764613731613130623465653664
30313937313961393634396235333432656261353230353930376630623366386533333737663335
66376132333466386639313665633562323864383964633238373964666664333036363332363634
39626137303436376433373434386166346237663535366334383732316131393438663866643233
306531326330313964323762343438303137
