$ANSIBLE_VAULT;1.1;AES256
36303961316363323737363930613137366635656164656466303862643236376434643736333933
3934303637643266363561626265383065623835623062380a393962346661333165323762613535
33386434643533646638383931306633636139356638333863306631333263353262613563613532
3164383666303539310a396631313065633661626332316231346135643363306337303136373037
63323937363233656463323135663461383361616331366164666633623435333732636636303135
37373866613933313432393763636530333436333232383866313332356134666430383564376266
33313036623634396463656666633531643061393932333062383734393632653463623636616664
66653461373261303964393531396138356461623536643738303262393461643566313339303866
33366365316131643435643236653262363363633438633265366266646530666238373131623361
30626634613435323531636632306164346161363339396663323163333362373436373234666436
62623336396633393930623437353136376138343861613833336530636237343033623839333064
37313633366330646232366162336639383737663636306463663736323966613839343737613531
39363033366539303537643834616436616231396138323330333338623839336530333432633230
36313535356664633232633438376162613333653663356637323736363866373038353732386435
663935633462666536336332356435323539
