- name: Ensure QEMU configuration for multiarch podman builds
  become: yes
  shell: podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes
  changed_when: False
  when: ansible_os_family == 'Debian'
